services:
  backend:
    build:
      context: ./backend/BluDiet.API
    ports:
      - "5123:8080"
    # volumes:
    #   - ./backend/BluDiet.API:/app 
    #   - ~/.aspnet/https:/https:ro   # (Opcional) para certificados SSL
    env_file:
      - ./backend/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1 # Ayuda a .NET a detectar cambios en Docker
    networks:
      - bludiet-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app             # Sincroniza tu código de React
      - /app/node_modules           # IMPORTANTE: No borra las librerías del contenedor
    env_file:         # <--- Añade esto para que lea el archivo .env
      - ./frontend/.env
    networks:
      - bludiet-network

networks:
  bludiet-network:
    driver: bridge